const jCategory = [
  {
    index: 0,
    image: "../images/google.png",
    title: "Web Developer",
    rate: "R20000-30000/pm",
    av: "Full Time",
    companyName: "Google",
    location: "South Africa",
    vacancy: "01",
    hours: "50h / Week",
    description:
      "We are seeking a skilled and creative Web Developer to design, build, and maintain responsive websites and web applications. The ideal candidate should be proficient in HTML, CSS, and JavaScript, with experience using modern frameworks such as React, Vue, or Angular. You will collaborate closely with designers and backend developers to deliver user-friendly, accessible, and high-performing web experiences. A strong understanding of cross-browser compatibility, responsive design, and version control (Git) is essential. Experience working with APIs and optimizing for speed and SEO is a plus.",
    workplace: "Work from home",
    education: "Bachelor degree in any Computer Science Course",
    experience: "2 to 5 years",
  },
  {
    index: 1,
    image: "../images/uber.png",
    title: "Business Associate",
    rate: "R10000-25000/pm",
    av: "Part Time",
    companyName: "Uber",
    location: "South Africa",
    vacancy: "08",
    hours: "40h / Week",
    description:
      "Uber is a global technology company that connects riders with drivers, and businesses with delivery solutions through its innovative mobile platform. Known for revolutionizing urban transportation, Uber operates in over 60 countries and continues to expand into new services such as food delivery and freight logistics.",
    workplace: "Work from office",
    education: "Degree in any Computer Science Course",
    experience: "1 to 5 years",
  },

  {
    index: 2,
    image: "../images/instagram.png",
    title: "Product Designer",
    rate: "R15000-25000/pm",
    av: "Part Time",
    companyName: "Instagram",
    location: "South Africa",
    vacancy: "02",
    hours: "0h / Week",
    description:
      "Instagram is a globally recognized social media platform that enables people to connect, share photos and videos, and discover content from around the world. As part of Meta Platforms, Instagram focuses on visual storytelling, community engagement, and innovative features like Stories, Reels, and IG Live. The company fosters a creative and fast-paced environment where teams build tools that empower individuals, creators, and businesses to express themselves and grow their audiences.",
    workplace: "Work from office",
    education: "Degree in any Computer Science Course",
    experience: "1 to 5 years",
  },

  {
    index: 3,
    image: "../images/apple.png",
    title: "Web Developer",
    rate: "R25000-35000/pm",
    av: "Full Time",
    companyName: "Apple",
    location: "South Africa",
    vacancy: "08",
    hours: "40h / Week",
    description:
      "Apple is seeking a talented and detail-oriented Web Developer to help design, build, and maintain high-quality web experiences that reflect Apple’s brand excellence. The ideal candidate will be proficient in HTML, CSS, JavaScript, and modern frameworks, with a passion for creating responsive, user-focused designs. You will collaborate with cross-functional teams to deliver seamless, scalable, and innovative web solutions that support Apple’s global digital presence.",
    workplace: "Work from home",
    education: "Degree in any Computer Science Course",
    experience: "1 to 5 years",
  },

  {
    index: 4,
    image: "../images/yahoo.png",
    title: "User Experience",
    rate: "R15000-25000/pm",
    av: "Full Time",
    companyName: "Yahoo",
    location: "South Africa",
    vacancy: "04",
    hours: "0h / Week",
    description:
      "Yahoo is a leading global technology and media company that delivers innovative digital content, experiences, and products to millions of users worldwide. Known for its long-standing presence in internet services, Yahoo offers a wide range of platforms including Yahoo News, Finance, Sports, Mail, and Advertising. The company focuses on creating engaging content and personalized experiences through data-driven technology, while also providing businesses with performance-based advertising solutions. With a dynamic and collaborative work culture, Yahoo empowers its employees to drive innovation in media, technology, and digital marketing.",
    workplace: "Work from office",
    education: "Degree in any Computer Science Course",
    experience: "1 to 5 years",
  },

  {
    index: 5,
    image: "../images/facebook.png",
    title: "Digital Marketing",
    rate: "R15000-25000/pm",
    av: "Full Time",
    companyName: "Facebook",
    location: "South Africa",
    vacancy: "08",
    hours: "40h / Week",
    description:
      "Facebook (Meta) is a global leader in social technology, connecting billions of people through its suite of apps including Facebook, Instagram, and WhatsApp. The company focuses on building innovative products that foster community, enable communication, and empower businesses worldwide. Known for its fast-paced and dynamic work environment, Facebook drives cutting-edge advancements in social networking, virtual reality, and AI.",
    workplace: "Work from office",
    education: "Degree in any Computer Science Course",
    experience: "1 to 5 years",
  },

  {
    index: 6,
    image: "../images/linkedin.png",
    title: "Business Associate",
    rate: "R10000-15000/pm",
    av: "Part Time",
    companyName: "Linkedin",
    location: "South Africa",
    vacancy: "08",
    hours: "40h / Week",
    description:
      "LinkedIn is the world’s largest professional networking platform, connecting millions of professionals and businesses globally. It enables users to build their professional brand, discover job opportunities, and grow their careers through networking, learning, and insights. LinkedIn also provides powerful tools for recruiters and companies to find and hire the right talent efficiently.",
    workplace: "Work from office",
    education: "Degree in any Computer Science Course",
    experience: "2 to 5 years",
  },

  {
    index: 7,
    image: "../images/wordpress.png",
    title: "Freelancer",
    rate: "R15000-25000/pm",
    av: "freelancer",
    companyName: "WorkWave",
    location: "South Africa",
    vacancy: "08",
    hours: "40h / Week",
    description:
      "Freelancers are independent professionals who offer their skills and expertise on flexible, project-based contracts. They work across diverse fields, delivering quality results while managing their own schedules. Our platform connects freelancers with clients seeking talented individuals for short-term and long-term projects.",
    workplace: "Work from home",
    education: "Degree in any Computer Science Course",
    experience: "1 to 5 years",
  },
];
